# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcbba47960271dc4be9a971f35c205ad4a965fbb46b2084145bbe389b3d6c8eafeacf5e3bdb188ad7197da13ad03ab7c6020472f0f8b1285784249b40e482c87

test:
  secret_key_base: ad5fe4a819c6218ad78d603d841ef58cb0bec8c4e296bb871f11f982f0630c371ca975a1760f3311cef9410b37439e452b9b539fc5665ead8d556deb0e9861d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
